# Netlify Configuration File
# This redirects all traffic to the primary domain

# Redirect from old domain to new domain
[[redirects]]
    from = "/*"
    to = "https://wellingtontimes.co.nz/:splat"
    status = 301
    force = true

# Build settings
[build]
    publish = "."
    
# Security headers
[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "strict-origin-when-cross-origin"
