# Netlify Configuration File
# Redirects old domain (wgtnews.live) to new domain (wellingtontimes.co.nz)

# Redirect from wgtnews.live to wellingtontimes.co.nz
[[redirects]]
  from = "https://wgtnews.live/*"
  to = "https://wellingtontimes.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.wgtnews.live/*"
  to = "https://wellingtontimes.co.nz/:splat"
  status = 301
  force = true

# Redirect www to non-www for new domain
[[redirects]]
  from = "https://www.wellingtontimes.co.nz/*"
  to = "https://wellingtontimes.co.nz/:splat"
  status = 301
  force = true

# Build settings
[build]
    publish = "."
    
# Security headers
[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "strict-origin-when-cross-origin"
